#!/usr/bin/env python
import json
import sys
import re
# Allow filtering a large leaks file that uses the gitleaks format, 
# like for example a file generated by the script "online-scan-secrets-consolidate.py".
#
# The output allow to search for specific secrets using grep with differents regexes like
# grep -B 4 -E 'ey[A-Za-z0-9]{15,}\.[A-Za-z0-9]{15,}\.[A-Za-z0-9_-]*' report.txt
def keep_leak(leak_json_entry):
    # Keep a leak by default
    keep = True
    src_file = leak["File"].replace("\\","/")
    content = leak["Secret"]
    if src_file.endswith(".css") or src_file.endswith(".less") or src_file.endswith(".scss"):
        keep = False
    elif "node_modules/" in src_file:
        keep = False
    return keep


report = sys.argv[1]
with open(report) as f:
    content = f.read()
leaks = json.loads(content)
with open("report.txt",mode="w",encoding="utf-8") as out:
    for leak in leaks:
        if not keep_leak(leak):
            continue
        a=leak["Author"]    
        f=leak["File"]    
        s=leak["Secret"]
        if "RepositoryURL" in leak:
            r=leak["RepositoryURL"]
        else:
            r="NA"
        c=leak["Commit"]
        out.write(f"------\nRepo  : {r}\nAuthor: {a}\nFile  : {f}\nCommit: {c}\nSecret: {s[:150]}\n")
        
