name: POC00 - Update the SemGrep scan reports of sandboxes codebase
on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths:
      - "misc/poc00/vulnerable-codebase/**"  
permissions: read-all   
jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Update the scans
        run: cd misc/poc00; chmod +x update-semgrep-scan-reports.sh; bash update-semgrep-scan-reports.sh
      - name: Update report files
        run: git config --global user.email "gha@github.com"; git config --global user.name "GHActionBot"; git commit -m "Sync SemGrep report file" misc/poc00/findings-*.json; git push
